// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGOSAcplYk766h5GRiH7BxjQzAfZ5xDY',
    appId: '1:886364664177:web:b4b91cc0ef6037e26d06d0',
    messagingSenderId: '886364664177',
    projectId: 'trpg-213c1',
    authDomain: 'trpg-213c1.firebaseapp.com',
    storageBucket: 'trpg-213c1.firebasestorage.app',
    measurementId: 'G-3DD98P04G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWA5RkrR6h3Su86KnAXQwrNcn0o4xwsvQ',
    appId: '1:886364664177:android:1fc6d9220d0801776d06d0',
    messagingSenderId: '886364664177',
    projectId: 'trpg-213c1',
    storageBucket: 'trpg-213c1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_a06i90BiR_68yGvqG6Bv-KLcom55w4',
    appId: '1:886364664177:ios:3065c051195047926d06d0',
    messagingSenderId: '886364664177',
    projectId: 'trpg-213c1',
    storageBucket: 'trpg-213c1.firebasestorage.app',
    iosClientId: '886364664177-m8v2b3o8vrfanc7gua5bu0thnk96nub7.apps.googleusercontent.com',
    iosBundleId: 'com.trpg.game.sotryTrpg',
  );
}
